# FILE: docker-compose.yml
version: '3.8'

services:
  # The Redis message queue that connects the API and the worker
  redis:
    image: redis:7-alpine
    container_name: logicore-redis
    networks:
      - logicore-net

  # The lightweight API service that just receives webhooks
  api:
    build:
      context: ./api
    container_name: logicore-api-service
    depends_on:
      - redis
    ports:
      - "8001:8001" # Expose the API port
    networks:
      - logicore-net
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  # The heavy-lifting worker service that runs CodeQL
  worker:
    build:
      context: ./worker
    container_name: logicore-worker-service
    depends_on:
      - redis
    networks:
      - logicore-net
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    # Give the worker more memory, as CodeQL can be memory intensive
    mem_limit: 4g

  # The ngrok tunnel for exposing the API service
  ngrok:
    image: ngrok/ngrok:latest
    container_name: logicore-ngrok-tunnel
    ports:
      - "4040:4040"
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    # This now points to the 'api' service on port 8001
    command: http api:8001
    networks:
      - logicore-net

networks:
  logicore-net: